#!/bin/bash
# hilow--A simple number-guessing game

biggest=10                    # max value for random 32bit integer
guess=0                       # guess made by player
guesses=1                     # number of guesses made
min=0                         # min value for random 32bit integer
number=$((SRANDOM % (biggest - min + 1) + min))  # generate 'UNIFORM' random number

# function to initialize new game
init_new_game() {
/bin/echo -n "Guess a number between $min and $biggest: " ; read -r guess
}

# function to initialize prompt for game in progress
init_game() {
/bin/echo -n "Guess a $hint number between $min and $biggest: " ; read -r guess
}

# function to check data is of the correct type
check_datatype() {
nodigits="$(echo "$guess" | sed 's/[[:digit:]]//g')"  # Create a version of the number that has no digits, for testing.
if [ -n "$nodigits" ] ; then  # Check for non-digit characters.
    echo "Invalid number format! Only digits, no commas, spaces, etc" >&2
	type=1
else
	type=0
fi
}

# function to check data is in the right range
check_range() {
if [ "$guess" -lt "$min" ] || [ "$guess" -gt "$biggest" ]; then # check the value is in the right range
	echo "Guess a number in this range! $min : $biggest"
	range=1
else
	range=0
fi
}

# function to loop the prompt till user inputs correct data type in the specified range
data_check() {
check_datatype
while [ "$type" == 1 ] ; do
	init_new_game
	check_datatype
done
check_range
while [ "$range" == 1 ] ; do
	init_new_game
	check_range
done
}

#function to evaluate guess
eval_guess() {
if [ "$guess" -lt "$number" ]; then
	hint="bigger"
elif [ "$guess" -gt "$number" ]; then
	hint="smaller"
fi
guesses=$(( guesses + 1 ))
}

# Beginning of game
init_new_game
data_check
while [ "$guess" -ne "$number" ] ; do
	eval_guess
	init_game
done
echo "Right!! Guessed $number in $guesses guesses."

exit 0