#!/bin/bash
# hilow--A number-guessing game

biggest=10                    # max value for random 32bit integer
guess=0                       # guess made by player
guesses=1                     # number of guesses made
min=0                         # min value for random 32bit integer
number=$((RANDOM % (biggest - min + 1) + min))  # generate 'UNIFORM' random number

# function to initialize prompt for game in progress
init_game() {
read -rp "Guess a $1number between $min and $biggest: " guess
}

# integer check
is_integer() { 
  case "${1#[-+]}" in 
    (''|*[!0-9]*) return 1 ;;
  esac
  return 0
}

# function to check data is of the correct type
data_check() {
until is_integer "$guess"; do  # Check for non-digit characters.
    echo "Invalid number format! Only digits, no commas, spaces, etc" >&2
	return 1
done
while [ "$guess" -lt "$min" ] || [ "$guess" -gt "$biggest" ]; do # check the value is in the right range
	echo "Guess a number in this range! $min : $biggest"
	return 1
done
return 0
}

#function to evaluate guess
eval_guess() {
		if ((guess < number)); then
				hint="bigger "
		elif ((guess > number)); then
				hint="smaller "
		fi
		((guesses++))
}

# Beginning of game
init_game
until data_check; do
	init_game
done
while [ "$guess" -ne "$number" ] ; do
	eval_guess
	init_game "$hint"
done
echo "Right!! Guessed $number in $guesses guesses."

exit 0
